apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: dice
spec:
  schedule: "*/1 * * * *" # minute hour dayOfMonth month dayofWeek
  jobTemplate:
    spec:
      completions: 1
      backoffLimit: 25 # This is so the job does not quit before it succeeds.
      activeDeadlineSeconds: 20
      template:
        spec:
          containers:
            - name: dice
              image: kodekloud/throw-dice
              imagePullPolicy: IfNotPresent

          restartPolicy: Never/OnFailure
