apiVersion: v1
kind: Pod
metadata: 
	name: taintsandtolerationa
spec: 
	containers: 
		- name: nginx-containers
		  image: nginx
	
	nodeSelector:
        size: Large
          
          
kubectl label nodes node-name labe-key=label-value

    taint-effect 3 typs:
        NoSchedule, PreferNoSchedule, NoExecute
        
 Ex: kubectl label nodes node1 size=Large
 
 
    To Ensure PODS are nodes are hosted in a particular Nodes